[package]
name         = "cryptobox"
version      = "0.7.1"
authors      = ["Wire Swiss GmbH <support@wire.com>"]
description  = "High-level API for proteus with persistent storage."
homepage     = "https://github.com/wireapp/cryptobox"
repository   = "git@github.com:wireapp/cryptobox.git"
license      = "GPL-3.0"

[dependencies]
byteorder  = ">  0.3.0"
cbor-codec = ">= 0.4.1"

[dependencies.proteus]
git    = "https://github.com/wireapp/proteus"
branch = "develop"
