[package]

name         = "cryptobox"
version      = "0.1.0"
authors      = ["Roman S. Borschel <roman@pkaboo.org>", "Toralf Wittner <tw@dtex.org>"]
description  = "High-level C API with persistent storage for the proteus implementation of the axolotl protocol."
homepage     = "https://github.com/romanb/cryptobox"
repository   = "git@github.com:romanb/cryptobox.git"
license      = "MPL-2.0"

[lib]

name         = "cryptobox"
crate-type   = ["dylib"]

[dependencies]
rustc-serialize = "> 0.2"

[dependencies.proteus]
git    = "https://github.com/twittner/proteus"
branch = "chacha20"
